### ISSUE TITLE
Failed to Generate Project Files

### ISSUE THREAD

**Issue by myself-piyush** [tomlooman/EpicSurvivalGame#72]
error CS2021: File name 'C:\Users\piyu\Downloads\Unreal Engine 4 Mastery Create Multiplayer Games with C++\[Tutsgalaxy.com] - Unreal Engine 4 Mastery Create Multiplayer Games with C++\2. Stealth Game 1 Project Basics\StealthGameTemplate417\Intermediate\Build\BuildRules\FPSGameMod' is too long or invalid
ERROR: Unable to compile source files.

Please Help Me

**Comment by tomlooman** [comment]
Please think before you ask for help on my pirated course.

**Comment by tomlooman** [comment]
Please think before you ask for help on my pirated course.
